apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: temperaturas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: a27959svalero/temperaturas-backend:v1
        ports:
        - containerPort: 5000